"""Regenerate the static catalog and sync publisher logos after editing assets/apps.json."""
import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
catalog = json.loads((ROOT / "assets/apps.json").read_text("utf-8"))
assert len({a["id"] for a in catalog}) == len(catalog)
for entry in catalog:
    assert (ROOT / "assets/logos" / entry["logo"]).is_file(), entry["id"]
script = "// Generated by tools/sync_apps.py from assets/apps.json.\nwindow.FLOW_APPS = " + json.dumps(catalog, ensure_ascii=False, separators=(",", ":")) + ";\n"
(ROOT / "assets/apps.js").write_text(script, "utf-8")
shutil.copy2(ROOT / "assets/apps.js", ROOT / "site/assets/apps.js")
for entry in catalog:
    shutil.copy2(ROOT / "assets/logos" / entry["logo"], ROOT / "site/assets/logos" / entry["logo"])
shutil.copy2(ROOT / "assets/logos/SOURCES.txt", ROOT / "site/assets/logos/SOURCES.txt")
print(f"Synced {len(catalog)} app identities and logos")
